### PR TITLE
Cleanup clashing type InvalidMessage. This was defined for the same p…

### PR DESCRIPTION
**Pull request by WaatzeG**
…ackage in two repositories. This one can be deleted

### CODE REVIEW

**Comment by bmjansen** [comment]
Is this the right repository to remove it from then? System integrators will only use the code from this repository, not from others like our commons.

**Comment by jasperkremer** [comment]
InvalidMessage is not used at all by retail-services-API. So it is unlikely that System integrators are using this class as well.

**Comment by jasperkremer** [comment]
We can also increase major version first and then remove this class (breaking change)

**Comment by jasperkremer** [comment]
I have upgraded version number. I will merge it.

**Pull request merged**
